### ISSUE TITLE
Tokens File Missing

### ISSUE THREAD

**Issue by Diogovski** [JReverse/JRaidRewritten#5]
Hi, i keep getting an error saying tokens.txt file missing, i checked the folder and noticed that indeed there isn't such file, sooooo. What i do now? Can i simply create the file and type the coins their?

**Comment by JReverse** [comment]
@Diogovski yes.

**Comment by Diogovski** [comment]
Do you know what's the problem?

A sábado, 10/04/2021, 14:18, J ***@***.***> escreveu:

**Comment by Diogovski** [comment]
Ignore the last email, pls.

A sábado, 10/04/2021, 15:23, Diogo Ribeiro ***@***.***>
escreveu:
